### ISSUE TITLE
Customize opengraph tags per page

### ISSUE THREAD

**Issue by tiltec** [yunity/yunity.org#15]
should show a page summary, maybe another image for blog posts.

**Comment by djahnie** [comment]
Started doing this. Sadly, I have no idea how to test if this works locally, because when I e.g. copy&paste the localhost links to Slack nothing happens, but I guess that's because of the localhost in the links... Hm dunno, I'll just commit something and see if I was terribly wrong or not... xD
Because, of course, I _think_ that I'm not...^^

But that's why I just did it for the subpages only and not for every single blog post so far...

**Comment by tiltec** [comment]
Looks pretty good: https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fyunity.org%2Fen%2Fheartbeat

Except for the circular redirect. I guess we should always put the "en" in the link (or automatically derive from the base URL, that should be possibly in Grav).
For the blog posts, a template would be better instead of adding the metadata to every post individually.

**Comment by djahnie** [comment]
Yay! ^^
Okay, so I'll add the "en" to the links.
How would a template work? Would it be the same for every post or somehow automatically adapt to the respective content? And where to put it, in the main page of the blog..? (If you could just give me a link to read it up or some useful phrase to google, I'll try to do this on my own...)

**Comment by tiltec** [comment]
This should do: https://github.com/paulcmal/grav-plugin-socialmeta/blob/master/templates/partials/socialmeta.html.twig

There's more instructions in the Readme.md, but essentially you copy over the partial (instead of cloning) and embed it.

We need to remove our explicit defaults https://github.com/yunity/yunity.org/commit/6cb098b8aae9b167b6c8ee7fecea5fe9be978363 to make the template work (I guess). And we should modify it to default to the yunity logo if no other picture could be found.
